### ISSUE TITLE
Error on pxt serve

### ISSUE THREAD

**Issue by coderkidz** [microsoftsam/pxt-holidays#4]
Hi, 
Thanks for such a great example. 
I have cloned this project, and followed the instructions, but I get this error message:
Using target PXT/holidays with build engine none
  Target dir:   D:\Projects\pxt-holidays
  PXT Core dir: D:\Projects\pxt-holidays\node_modules\pxt-core
log strings: 48 files; 0 strings -> sim-strings.json
error TS6053: File 'D:/Projects/pxt-holidays/node_modules/pxt-core/built/lib.dom.d.ts' not found.
error TS6053: File 'D:/Projects/pxt-holidays/node_modules/pxt-core/built/lib.dom.iterable.d.ts' not found.
error TS6053: File 'D:/Projects/pxt-holidays/node_modules/pxt-core/built/lib.es2015.d.ts' not found.
error TS6053: File 'D:/Projects/pxt-holidays/node_modules/pxt-core/built/lib.scripthost.d.ts' not found.
error TS2318: Cannot find global type 'Array'.
error TS2318: Cannot find global type 'Boolean'.
error TS2318: Cannot find global type 'Function'.
error TS2318: Cannot find global type 'IArguments'.
error TS2318: Cannot find global type 'Number'.
error TS2318: Cannot find global type 'Object'.
error TS2318: Cannot find global type 'RegExp'.
error TS2318: Cannot find global type 'String'.
building sim...
[run] cd sim; node ../node_modules/typescript/bin/tsc
building target.json in D:\Projects\pxt-holidays...
building docs in libs/core
Package built; written to binary.hex; size: 0
generated _locales\core-strings.json; size=2293
generated _locales\core-jsdoc-strings.json; size=8945
building libs/core
  skip native build of non-project
building libs\blocksprj
target.json built.
building cmds...
[run] cd cmds; node ../node_modules/typescript/bin/tsc
../node_modules/pxt-core/built/pxtlib.d.ts(5,23): error TS2688: Cannot find type definition file for 'marked'.
../node_modules/pxt-core/built/pxtlib.d.ts(424,37): error TS2304: Cannot find name 'marked'.

***
*** Build failed: target build failed: Exit code: 2 from cd cmds; node ../node_modules/typescript/bin/tsc
Error: Exit code: 2 from cd cmds; node ../node_modules/typescript/bin/tsc
    at ChildProcess.<anonymous> (D:\Projects\pxt-holidays\node_modules\pxt-core\built\nodeutil.js:86:24)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:957:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:5)
***

watching D:\Projects\pxt-holidays\node_modules\pxt-core, libs/core, theme, theme\site\globals, editor, sim, sim\public, cmds...
Starting server in D:\Projects\pxt-holidays
With pxt core at D:\Projects\pxt-holidays\node_modules\pxt-core
starting local ws server at 3233...
---------------------------------------------

Could you please help me.
Thanks.

**Comment by ghost** [comment]
I have the identical error, pxt 0.5.1

**Comment by samelhusseini** [comment]
no worries, I will take a look into this error tonight. it’s most likely a dependency that needs to be added or upgraded.

**Comment by samelhusseini** [comment]
I’ve fixed up this sample and updated it to the latest pxt-core. Please pull and let me know if you’re still running into any issues

**Comment by samelhusseini** [comment]
This is fixed, closing.
