### ISSUE TITLE
Can't add/change name of block categories

### ISSUE THREAD

**Issue by NoobDoesMC** [microsoftsam/pxt-holidays#7]
Remove `hideCategories` line from `pxtarget.json`

Try adding 

```ts
//% color=190 weight=100 icon="\uf1ec" block="Test"
namespace pxsim.test {
  //% blockId=return_one block="return one"
  export function sayit(): number {
    return 1;
  }
}
```

to `sim/api.ts` and then `pxt serve`.

It makes a new grey category that crashes the toolbar when it is clicked

![screenshot 2018-12-11 at 21 00 22](https://user-images.githubusercontent.com/29206206/49831470-e17ac100-fd8b-11e8-8312-27d068606be6.png)
![screenshot 2018-12-11 at 21 00 28](https://user-images.githubusercontent.com/29206206/49831471-e17ac100-fd8b-11e8-8fd9-88303a055dd3.png)

**Comment by samelhusseini** [comment]
So a couple of things here. Looks like there's a bug with the default namespace color if it's not set which I can fix in pxt-core, but there's a workaround. 

Add the following in libs/ns.ts
```

//% color=190
namespace test {

}

```

**Comment by NoobDoesMC** [comment]
@samelhusseini that workaround didn't work?

Unless it isn't meant to work yet? I guess I can update my local `pxt` before `pxt update` will.

**Comment by samelhusseini** [comment]
The issue is only for inverted toolboxes, so you could also just change:
```
        "invertedToolbox": false,
```
to false in pxtarget.json until the fix is propagated.

**Comment by NoobDoesMC** [comment]
@samelhusseini how did you get your `card` and `lights` categories to display properly?

Removing the `invertedToolbox` line from `pxtarget.json` stops the crashing, but the color, icon, and weight are all still wrong.

**Comment by NoobDoesMC** [comment]
@samelhusseini but I still get the problem? The category is always grey with the puzzle icon.

**Comment by samelhusseini** [comment]
Sorry that was auto closed from pushing the PR. 
I think you still need to set the colour over in libs/ns.ts. Have you tried that?

**Comment by NoobDoesMC** [comment]
@samelhusseini Yeah.

`/libs/ns.ts`

```ts
//% color=190
namespace pxsim.blocks {
}
```

and inside of `/sim/api.ts` I added

```ts
//% color=190 weight=100 icon="\uf1ec" block="Blocks"
namespace pxsim.blocks {
  //% blockId=gargle block="set block"
  export function setBlock(): void {
    return;
  }
}
```

![screenshot 2018-12-12 at 21 31 00](https://user-images.githubusercontent.com/29206206/49899992-3d5d4c80-fe55-11e8-87a6-e45e635741b2.png)

**Comment by samelhusseini** [comment]
Your issue is that you added the namespace pxsim.blocks in ns.ts.

The namespace ``blocks``  under`` libs`` is mapped to ``pxsim.blocks`` under ``sim/`` and vice versa, so you should try setting the colour on the ``blocks`` namespace in ``libs/ns.ts``. ie:

```
//% color=190
namespace blocks {

}
```

**Comment by NoobDoesMC** [comment]
@samelhusseini that also doesn't work, it fails in the same way.

Oh, I just added it to `libs/core/ns.ts` and it seems to work now.

**Comment by samelhusseini** [comment]
Great!
